import type { ConstructionSite } from "./construction-site.types";

export const constructionSites: ConstructionSite[] = [
  {
    id: "1",
    slug: "industriehalle-linz",
    projectNumber: "BT-2026-001",
    name: "Industriehalle Linz",
    customerName: "Müller Bau GmbH",
    address: "Industriestraße 15",
    postalCode: "4020",
    city: "Linz",
    status: "active",
    employeeCount: 12,
    startDate: "2026-07-01",
    managerName: "Patrik Kabashi",
  },
  {
    id: "2",
    slug: "wohnanlage-wien",
    projectNumber: "BT-2026-002",
    name: "Wohnanlage Wien",
    customerName: "Wohnbau AG",
    address: "Hauptstraße 88",
    postalCode: "1100",
    city: "Wien",
    status: "paused",
    employeeCount: 8,
    startDate: "2026-06-10",
    managerName: "Max Mustermann",
  },
  {
    id: "3",
    slug: "schule-graz",
    projectNumber: "BT-2026-003",
    name: "Schule Graz",
    customerName: "Stadt Graz",
    address: "Schulweg 7",
    postalCode: "8010",
    city: "Graz",
    status: "completed",
    employeeCount: 5,
    startDate: "2026-04-15",
    endDate: "2026-06-30",
    managerName: "Anna Berger",
  },
];